#!perl

require("includes/shared.pl");

$template = &openFile("templates/template.html");
$content = &openFile("templates/$scriptname.html");
&initFunctions;

if ($ENV{'REQUEST_METHOD'} eq "POST") {                                     # settings saved
    $app_name = &formatText($FORM{app_name});
    $app_name = ($app_name =~ /\w/)?$app_name:$DEFAULT_APPNAME;             # use default App name if no name is provided!
    $employee_name = &formatText($FORM{employee_name});
    $current_employer = &formatText($FORM{current_employer});
    $current_salary = &formatText($FORM{current_salary});
    $current_venue = &formatText($FORM{current_venue});
    $currency = &formatText($FORM{currency});
    $startup_page = $FORM{startup_page};
    
    $cquery = $dbh->prepare("select app_name from settings");
    $cquery->execute();
    $crows = $cquery->rows();
    if ($crows < 1) {
        $query = $dbh->prepare("insert into settings (app_name, employee_name, current_employer, current_salary, current_venue, currency, startup_page) values (\"$app_name\", \"$employee_name\", \"$current_employer\", '$current_salary', \"$current_venue\", \"$currency\", \"$startup_page\")");
        $query->execute();
    } else {
        $query = $dbh->prepare("update settings set app_name=\"$app_name\", employee_name=\"$employee_name\", current_employer=\"$current_employer\", current_salary='$current_salary', current_venue=\"$current_venue\", currency=\"$currency\", startup_page=\"$startup_page\" limit 1");
        $query->execute();
    }
    $rows = $query->rows();
    if ($rows > 0) {
        $query = $dbh->prepare("select rate from account_settings order by since DESC limit 1");
        $query->execute();
        $srows = $query->rows();
        $data = $query->fetchrow_hashref;                                   # add new salary/rate if it's not the same
        if ($srows < 1 || (($current_salary =~ /\d+/ && $$data{rate} =~ /\d+/) && ($$data{rate} ne $current_salary || $$data{rate} != $current_salary))) {
            $dbh->do("insert into account_settings (employee_name, employer_name, rate, since) values (\"$employee_name\", \"$current_employer\", '$current_salary', now())");
        }
        print "Location:$path/$scriptname\n\n";                             # redirect back to settings page, so changes reflect immediately e.g., App name on <h1> heading
    } else { &displayMsg(1, "Update failed! Try again."); }
}

$elist = &getEmployersList;
$content =~ s|<!--EMPLOYERS_LIST-->|$elist|;

$query = $dbh->prepare("select * from settings");                           # load current settings
$query->execute();
$data = $query->fetchrow_hashref;
@ifields = ("app_name", "employee_name", "current_salary", "current_venue", "currency");
@sfields = ("current_employer", "startup_page");
foreach (@ifields) { $content =~ s|name="$_" value=""|name="$_" value="$$data{$_}"|; }
foreach (@sfields) { $content =~ s|<option value="$$data{$_}">|<option value="$$data{$_}" selected="selected">|; }

$template =~ s|<!--CONTENT-->|$content|;

print "Content-type:text/html\n\n";
print $template;